version: '3.4'

volumes:
  mysql-data:

services:
  
  mysql:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "weather"
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
